# Generated by Django 2.0.6 on 2018-06-14 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiledDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_level', models.IntegerField()),
                ('tile_count_on_x', models.IntegerField()),
                ('tile_count_on_y', models.IntegerField()),
                ('total_tile_count', models.IntegerField()),
                ('profile_file_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='tileddocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiler.Document'),
        ),
    ]
